# paths
PATH_PROGRAMONES = 'programones.csv'
PATH_ENTRENADORES = 'entrenadores.csv'
PATH_OBJETOS = 'objetos.csv'
PATH_EVOLUCIONES = 'evoluciones.csv'

# límites de properties
NIVEL_MIN = 1
NIVEL_MAX = 100
EXPERIENCIA_MIN = 0
EXPERIENCIA_MAX = 100
VIDA_MIN = 1
VIDA_MAX = 255
ATAQUE_MIN = 5
ATAQUE_MAX = 190
DEFENSA_MIN = 5
DEFENSA_MAX = 250
VELOCIDAD_MIN = 5
VELOCIDAD_MAX = 200
ENERGIA_MIN = 0
ENERGIA_MAX = 100

# entrenamiento
ENERGIA_ENTRENAMIENTO = 10
AUMENTO_EXPERIENCIA_MIN = 20
AUMENTO_EXPERIENCIA_MAX = 60
AUMENTO_ENTRENAMIENTO_MIN = 2
AUMENTO_ENTRENAMIENTO_MAX = 5

# batallas ganados
AUMENTO_VELOCIDAD_AGUA = 8
AUMENTO_ATAQUE_FUEGO = 6
AUMENTO_VIDA_PLANTA = 8

# ponderación del puntaje de victoria
POND_VIDA = 0.2
POND_NIVEL = 0.3
POND_ATAQUE = 0.15
POND_DEFENSA = 0.15
POND_VELOCIDAD = 0.2
POND_VENTAJA = 40.0

# efectos de los objetos
AUMENTO_VIDA_MIN = 1
AUMENTO_VIDA_MAX = 10
AUMENTO_ATAQUE_MIN = 1
AUMENTO_ATAQUE_MAX = 7
AUMENTO_DEFENSA_MIN = 1
AUMENTO_DEFENSA_MAX = 7

# costo y creación de los objetos
GASTO_ENERGIA_BAYA = 10
PROB_EXITO_BAYA = 0.8
GASTO_ENERGIA_POCION = 10
PROB_EXITO_POCION = 0.8
GASTO_ENERGIA_CARAMELO = 20
PROB_EXITO_CARAMELO = 0.8

# megaevoluciones
MEGA_VIDA = 20
MEGA_ATAQUE = 20
MEGA_DEFENSA = 20
MEGA_VELOCIDAD = 20

# gráficos
NUM_GUIONES_LINEA = 100